-- MySQL Script generated by MySQL Workbench
-- Mon Oct  4 07:03:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROOMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROOMS` (
  `roomId` INT NOT NULL,
  `floorNumber` INT NULL,
  `roomCapacity` VARCHAR(45) NULL,
  `roomContact` VARCHAR(45) NULL,
  PRIMARY KEY (`roomId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OFFICEROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OFFICEROOM` (
  `officeRoomId` INT NOT NULL,
  `floorNumber` INT NULL,
  `OfficeRoomCapacity` VARCHAR(45) NULL,
  `employeeId` VARCHAR(45) NULL,
  `ROOMS_roomId` INT NOT NULL,
  PRIMARY KEY (`officeRoomId`),
  INDEX `fk_OFFICEROOM_ROOMS1_idx` (`ROOMS_roomId` ASC),
  CONSTRAINT `fk_OFFICEROOM_ROOMS1`
    FOREIGN KEY (`ROOMS_roomId`)
    REFERENCES `mydb`.`ROOMS` (`roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESULT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESULT` (
  `employeeId` INT NOT NULL,
  `currentStatus` VARCHAR(45) NULL,
  `quarantineLocation` VARCHAR(45) NULL,
  `timeToOffice` VARCHAR(45) NULL,
  PRIMARY KEY (`employeeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `employeeId` INT NOT NULL,
  `employeeName` VARCHAR(45) NULL,
  `employeeAddress` VARCHAR(45) NULL,
  `employeePhoneNumber` VARCHAR(45) NULL,
  `employeeEmergencyContact` VARCHAR(45) NULL,
  `employeeRole` VARCHAR(45) NULL,
  `employeeSalary` VARCHAR(45) NULL,
  `employeeJoiningDate` VARCHAR(45) NULL,
  `employeeMailId` VARCHAR(45) NULL,
  `employeeTestingStatus` VARCHAR(45) NULL,
  `employeeLocation` VARCHAR(45) NULL,
  `OFFICEROOM_officeRoomId` INT NOT NULL,
  `RESULT_employeeId` INT NOT NULL,
  PRIMARY KEY (`employeeId`, `RESULT_employeeId`),
  INDEX `fk_Employees_OFFICEROOM1_idx` (`OFFICEROOM_officeRoomId` ASC),
  INDEX `fk_Employees_RESULT1_idx` (`RESULT_employeeId` ASC),
  CONSTRAINT `fk_Employees_OFFICEROOM1`
    FOREIGN KEY (`OFFICEROOM_officeRoomId`)
    REFERENCES `mydb`.`OFFICEROOM` (`officeRoomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_RESULT1`
    FOREIGN KEY (`RESULT_employeeId`)
    REFERENCES `mydb`.`RESULT` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TESTING_LOCATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TESTING_LOCATIONS` (
  `testingLocationId` INT NOT NULL,
  `testingLocation` VARCHAR(45) NULL,
  `testingLocationContact` VARCHAR(205) NULL,
  `testingLocationAddress` VARCHAR(205) NULL,
  `isOnPremise` TINYINT(1) NULL,
  PRIMARY KEY (`testingLocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FLOORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FLOORS` (
  `floorID` INT NOT NULL,
  `floorHead` VARCHAR(45) NULL,
  PRIMARY KEY (`floorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEETINGROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEETINGROOM` (
  `meetingRoomId` INT NOT NULL,
  `floorNumber` VARCHAR(45) NULL,
  `meetingRoomCapacity` VARCHAR(45) NULL,
  `meetingRoomContact` VARCHAR(45) NULL,
  `isMeetingRoom` TINYINT(1) NULL,
  `ROOMS_roomId` INT NOT NULL,
  `FLOORS_floorID` INT NOT NULL,
  PRIMARY KEY (`meetingRoomId`, `FLOORS_floorID`),
  INDEX `fk_MEETINGROOM_ROOMS1_idx` (`ROOMS_roomId` ASC),
  INDEX `fk_MEETINGROOM_FLOORS1_idx` (`FLOORS_floorID` ASC),
  CONSTRAINT `fk_MEETINGROOM_ROOMS1`
    FOREIGN KEY (`ROOMS_roomId`)
    REFERENCES `mydb`.`ROOMS` (`roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEETINGROOM_FLOORS1`
    FOREIGN KEY (`FLOORS_floorID`)
    REFERENCES `mydb`.`FLOORS` (`floorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEETINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEETINGS` (
  `meetingId` INT NOT NULL,
  `floorNumber` VARCHAR(45) NULL,
  `meetingRoomId` VARCHAR(45) NULL,
  `meetingStartTime` VARCHAR(45) NULL,
  `meetingEndTime` VARCHAR(45) NULL,
  `meetingDate` VARCHAR(45) NULL,
  `meetingManager` VARCHAR(45) NULL,
  PRIMARY KEY (`meetingId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TESTING_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TESTING_STATUS` (
  `employeeId` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `lastTestingLocation` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `lastTestingTime` VARCHAR(45) NULL,
  `symptoms` VARCHAR(45) NULL,
  PRIMARY KEY (`employeeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TESTING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TESTING` (
  `testingId` INT NOT NULL,
  `employeeId` VARCHAR(45) NULL,
  `timeStamp` VARCHAR(45) NULL,
  `lastMeetingId` VARCHAR(45) NULL,
  `officeRoomId` VARCHAR(45) NULL,
  `testingLocation` VARCHAR(45) NULL,
  `TESTING_LOCATIONS_testingLocationId` INT NOT NULL,
  `testingType` VARCHAR(45) NULL,
  `isRandom` TINYINT(1) NULL,
  `TESTING_STATUS_employeeId` INT NOT NULL,
  `Employees_employeeId` INT NOT NULL,
  `Employees_RESULT_employeeId` INT NOT NULL,
  PRIMARY KEY (`testingId`, `TESTING_LOCATIONS_testingLocationId`, `Employees_employeeId`, `Employees_RESULT_employeeId`),
  INDEX `fk_TESTING_TESTING_LOCATIONS1_idx` (`TESTING_LOCATIONS_testingLocationId` ASC),
  INDEX `fk_TESTING_TESTING_STATUS1_idx` (`TESTING_STATUS_employeeId` ASC),
  INDEX `fk_TESTING_Employees1_idx` (`Employees_employeeId` ASC, `Employees_RESULT_employeeId` ASC),
  CONSTRAINT `fk_TESTING_TESTING_LOCATIONS1`
    FOREIGN KEY (`TESTING_LOCATIONS_testingLocationId`)
    REFERENCES `mydb`.`TESTING_LOCATIONS` (`testingLocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TESTING_TESTING_STATUS1`
    FOREIGN KEY (`TESTING_STATUS_employeeId`)
    REFERENCES `mydb`.`TESTING_STATUS` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TESTING_Employees1`
    FOREIGN KEY (`Employees_employeeId` , `Employees_RESULT_employeeId`)
    REFERENCES `mydb`.`Employees` (`employeeId` , `RESULT_employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SELF_REPORT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SELF_REPORT` (
  `reportId` INT NOT NULL,
  `employeeId` VARCHAR(45) NULL,
  `timeStamp` VARCHAR(45) NULL,
  `meetingId` VARCHAR(45) NULL,
  `officeRoomId` VARCHAR(45) NULL,
  `symptomId` VARCHAR(45) NULL,
  `TESTING_testingId` INT NOT NULL,
  `TESTING_TESTING_LOCATIONS_testingLocationId` INT NOT NULL,
  `Employees_employeeId` INT NOT NULL,
  `Employees_RESULT_employeeId` INT NOT NULL,
  PRIMARY KEY (`reportId`, `Employees_employeeId`, `Employees_RESULT_employeeId`),
  INDEX `fk_SELF_REPORT_TESTING1_idx` (`TESTING_testingId` ASC, `TESTING_TESTING_LOCATIONS_testingLocationId` ASC),
  INDEX `fk_SELF_REPORT_Employees1_idx` (`Employees_employeeId` ASC, `Employees_RESULT_employeeId` ASC),
  CONSTRAINT `fk_SELF_REPORT_TESTING1`
    FOREIGN KEY (`TESTING_testingId` , `TESTING_TESTING_LOCATIONS_testingLocationId`)
    REFERENCES `mydb`.`TESTING` (`testingId` , `TESTING_LOCATIONS_testingLocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SELF_REPORT_Employees1`
    FOREIGN KEY (`Employees_employeeId` , `Employees_RESULT_employeeId`)
    REFERENCES `mydb`.`Employees` (`employeeId` , `RESULT_employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NOTIFICATION` (
  `notificationId` INT NOT NULL,
  `employeeId` VARCHAR(45) NULL,
  `employeePhoneNumber` VARCHAR(45) NULL,
  `employeeMailId` VARCHAR(45) NULL,
  `symptomDetails` VARCHAR(45) NULL,
  `HR Details` VARCHAR(45) NULL,
  `HR Contacts` VARCHAR(45) NULL,
  PRIMARY KEY (`notificationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attends` (
  `Employees_employeeId` INT NOT NULL,
  `MEETINGS_meetingId` INT NOT NULL,
  PRIMARY KEY (`Employees_employeeId`, `MEETINGS_meetingId`),
  INDEX `fk_Employees_has_MEETINGS_MEETINGS1_idx` (`MEETINGS_meetingId` ASC),
  INDEX `fk_Employees_has_MEETINGS_Employees1_idx` (`Employees_employeeId` ASC),
  CONSTRAINT `fk_Employees_has_MEETINGS_Employees1`
    FOREIGN KEY (`Employees_employeeId`)
    REFERENCES `mydb`.`Employees` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_has_MEETINGS_MEETINGS1`
    FOREIGN KEY (`MEETINGS_meetingId`)
    REFERENCES `mydb`.`MEETINGS` (`meetingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEETINGS_has_MEETINGROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEETINGS_has_MEETINGROOM` (
  `MEETINGS_meetingId` INT NOT NULL,
  `MEETINGROOM_meetingRoomId` INT NOT NULL,
  PRIMARY KEY (`MEETINGS_meetingId`, `MEETINGROOM_meetingRoomId`),
  INDEX `fk_MEETINGS_has_MEETINGROOM_MEETINGROOM1_idx` (`MEETINGROOM_meetingRoomId` ASC),
  INDEX `fk_MEETINGS_has_MEETINGROOM_MEETINGS1_idx` (`MEETINGS_meetingId` ASC),
  CONSTRAINT `fk_MEETINGS_has_MEETINGROOM_MEETINGS1`
    FOREIGN KEY (`MEETINGS_meetingId`)
    REFERENCES `mydb`.`MEETINGS` (`meetingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEETINGS_has_MEETINGROOM_MEETINGROOM1`
    FOREIGN KEY (`MEETINGROOM_meetingRoomId`)
    REFERENCES `mydb`.`MEETINGROOM` (`meetingRoomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees_has_NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees_has_NOTIFICATION` (
  `Employees_employeeId` INT NOT NULL,
  `Employees_RESULT_employeeId` INT NOT NULL,
  `NOTIFICATION_notificationId` INT NOT NULL,
  PRIMARY KEY (`Employees_employeeId`, `Employees_RESULT_employeeId`, `NOTIFICATION_notificationId`),
  INDEX `fk_Employees_has_NOTIFICATION_NOTIFICATION1_idx` (`NOTIFICATION_notificationId` ASC),
  INDEX `fk_Employees_has_NOTIFICATION_Employees1_idx` (`Employees_employeeId` ASC, `Employees_RESULT_employeeId` ASC),
  CONSTRAINT `fk_Employees_has_NOTIFICATION_Employees1`
    FOREIGN KEY (`Employees_employeeId` , `Employees_RESULT_employeeId`)
    REFERENCES `mydb`.`Employees` (`employeeId` , `RESULT_employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_has_NOTIFICATION_NOTIFICATION1`
    FOREIGN KEY (`NOTIFICATION_notificationId`)
    REFERENCES `mydb`.`NOTIFICATION` (`notificationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTIFICATION_has_TESTING_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NOTIFICATION_has_TESTING_STATUS` (
  `NOTIFICATION_notificationId` INT NOT NULL,
  `TESTING_STATUS_employeeId` INT NOT NULL,
  PRIMARY KEY (`NOTIFICATION_notificationId`, `TESTING_STATUS_employeeId`),
  INDEX `fk_NOTIFICATION_has_TESTING_STATUS_TESTING_STATUS1_idx` (`TESTING_STATUS_employeeId` ASC),
  INDEX `fk_NOTIFICATION_has_TESTING_STATUS_NOTIFICATION1_idx` (`NOTIFICATION_notificationId` ASC),
  CONSTRAINT `fk_NOTIFICATION_has_TESTING_STATUS_NOTIFICATION1`
    FOREIGN KEY (`NOTIFICATION_notificationId`)
    REFERENCES `mydb`.`NOTIFICATION` (`notificationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTIFICATION_has_TESTING_STATUS_TESTING_STATUS1`
    FOREIGN KEY (`TESTING_STATUS_employeeId`)
    REFERENCES `mydb`.`TESTING_STATUS` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
